import { ListingCard } from "./types";
import { ExperienceData } from "@/components/ExperienceCard";
import { ServiceData } from "@/components/ServiceCard";

export const dummyHomes: ListingCard[] = [
  {
    id: 101,
    title: "Luxury Loft in White Town",
    location: "White Town, Pondicherry",
    city: "Pondicherry",
    country: "India",
    price_per_night: 12000,
    property_type: "Loft",
    rating: 4.9,
    review_count: 120,
    cover_photo: "https://picsum.photos/seed/home101/500/500",
    is_wishlisted: false,
  },
  {
    id: 102,
    title: "Heritage Villa with Pool",
    location: "North Goa, Goa",
    city: "Goa",
    country: "India",
    price_per_night: 25000,
    property_type: "Villa",
    rating: 4.8,
    review_count: 85,
    cover_photo: "https://picsum.photos/seed/home102/500/500",
    is_wishlisted: true,
  },
  {
    id: 103,
    title: "Cozy Cottage near Mall Road",
    location: "Shimla, Himachal Pradesh",
    city: "Shimla",
    country: "India",
    price_per_night: 6500,
    property_type: "Cottage",
    rating: 4.7,
    review_count: 210,
    cover_photo: "https://picsum.photos/seed/home103/500/500",
    is_wishlisted: false,
  },
  {
    id: 104,
    title: "Bungalow with Aravalli Views",
    location: "Jaipur, Rajasthan",
    city: "Jaipur",
    country: "India",
    price_per_night: 15000,
    property_type: "Bungalow",
    rating: 5.0,
    review_count: 42,
    cover_photo: "https://picsum.photos/seed/home104/500/500",
    is_wishlisted: false,
  },
  {
    id: 105,
    title: "Modern Apartment in Cyber City",
    location: "Gurgaon, Haryana",
    city: "Gurgaon",
    country: "India",
    price_per_night: 8000,
    property_type: "Apartment",
    rating: 4.6,
    review_count: 300,
    cover_photo: "https://picsum.photos/seed/home105/500/500",
    is_wishlisted: false,
  },
  {
    id: 106,
    title: "Treehouse Retreat in the Ghats",
    location: "Munnar, Kerala",
    city: "Munnar",
    country: "India",
    price_per_night: 11000,
    property_type: "Treehouse",
    rating: 4.9,
    review_count: 150,
    cover_photo: "https://picsum.photos/seed/home106/500/500",
    is_wishlisted: false,
  },
  {
    id: 107,
    title: "Penthouse Overlooking Marine Drive",
    location: "Mumbai, Maharashtra",
    city: "Mumbai",
    country: "India",
    price_per_night: 35000,
    property_type: "Penthouse",
    rating: 4.8,
    review_count: 95,
    cover_photo: "https://picsum.photos/seed/home107/500/500",
    is_wishlisted: true,
  },
  {
    id: 108,
    title: "Houseboat on Dal Lake",
    location: "Srinagar, Kashmir",
    city: "Srinagar",
    country: "India",
    price_per_night: 9500,
    property_type: "Houseboat",
    rating: 4.9,
    review_count: 67,
    cover_photo: "https://picsum.photos/seed/home108/500/500",
    is_wishlisted: false,
  },
];

export const dummyExperiences: ExperienceData[] = [
  {
    id: "e1",
    title: "Sunset kayak tour",
    location: "Goa, India",
    price: "From ₹2,500",
    rating: 4.9,
    imageUrl: "https://picsum.photos/seed/exp1/500/500",
    badge: "Bestseller",
  },
  {
    id: "e2",
    title: "Old Delhi Heritage Food Walk",
    location: "New Delhi, India",
    price: "From ₹1,800",
    rating: 5.0,
    imageUrl: "https://picsum.photos/seed/exp2/500/500",
  },
  {
    id: "e3",
    title: "Block Printing Workshop",
    location: "Jaipur, India",
    price: "From ₹1,200",
    rating: 4.8,
    imageUrl: "https://picsum.photos/seed/exp3/500/500",
    badge: "Popular",
  },
  {
    id: "e4",
    title: "Yoga and Meditation Retreat",
    location: "Rishikesh, India",
    price: "From ₹3,000",
    rating: 4.9,
    imageUrl: "https://picsum.photos/seed/exp4/500/500",
  },
  {
    id: "e5",
    title: "Backwaters Canoe Experience",
    location: "Alleppey, India",
    price: "From ₹1,500",
    rating: 4.7,
    imageUrl: "https://picsum.photos/seed/exp5/500/500",
  },
  {
    id: "e6",
    title: "Bollywood Dance Class",
    location: "Mumbai, India",
    price: "From ₹2,000",
    rating: 4.9,
    imageUrl: "https://picsum.photos/seed/exp6/500/500",
    badge: "New",
  },
  {
    id: "e7",
    title: "Trek to Triund Peak",
    location: "Dharamshala, India",
    price: "From ₹4,500",
    rating: 4.8,
    imageUrl: "https://picsum.photos/seed/exp7/500/500",
  },
  {
    id: "e8",
    title: "French Quarter Heritage Walk",
    location: "Pondicherry, India",
    price: "From ₹1,000",
    rating: 4.9,
    imageUrl: "https://picsum.photos/seed/exp8/500/500",
  },
];

export const dummyServices: ServiceData[] = [
  {
    id: "s1",
    title: "Bridal makeup by Sukoon",
    price: "From ₹15,000",
    rating: 4.9,
    imageUrl: "https://picsum.photos/seed/srv1/500/500",
    badge: "Popular",
  },
  {
    id: "s2",
    title: "Professional Photography Session",
    price: "From ₹5,000",
    rating: 4.8,
    imageUrl: "https://picsum.photos/seed/srv2/500/500",
  },
  {
    id: "s3",
    title: "Private Chef Experience",
    price: "From ₹8,000",
    rating: 5.0,
    imageUrl: "https://picsum.photos/seed/srv3/500/500",
    badge: "Premium",
  },
  {
    id: "s4",
    title: "Airport Transfer in Luxury SUV",
    price: "From ₹2,500",
    rating: 4.7,
    imageUrl: "https://picsum.photos/seed/srv4/500/500",
  },
  {
    id: "s5",
    title: "Deep House Cleaning",
    price: "From ₹3,000",
    rating: 4.9,
    imageUrl: "https://picsum.photos/seed/srv5/500/500",
  },
  {
    id: "s6",
    title: "Event Decoration & Planning",
    price: "From ₹20,000",
    rating: 4.8,
    imageUrl: "https://picsum.photos/seed/srv6/500/500",
    badge: "Bestseller",
  },
  {
    id: "s7",
    title: "Personal Trainer for a week",
    price: "From ₹4,000",
    rating: 4.9,
    imageUrl: "https://picsum.photos/seed/srv7/500/500",
  },
  {
    id: "s8",
    title: "Local Guide for City Tour",
    price: "From ₹1,500",
    rating: 4.8,
    imageUrl: "https://picsum.photos/seed/srv8/500/500",
  },
];
